# Generated by Django 5.2.3 on 2025-07-17 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("can_unpublish_product", "Может отменять публикацию продукта")
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
